// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveList(arg1) {
  return window['go']['main']['Todos']['SaveList'](arg1);
}

export function WailsInit() {
  return window['go']['main']['Todos']['WailsInit']();
}

export function LoadList() {
  return window['go']['main']['Todos']['LoadList']();
}

export function LoadNewList() {
  window['go']['main']['Todos']['LoadNewList']();
}

export function SaveAs(arg1) {
  return window['go']['main']['Todos']['SaveAs'](arg1);
}
