// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveList(arg1:string):Promise<Error>;

export function WailsInit():Promise<Error>;

export function LoadList():Promise<string|Error>;

export function LoadNewList():void;

export function SaveAs(arg1:string):Promise<Error>;
